Added option to pack a data folder

diff --git a/docker-pack b/docker-pack
--- a/docker-pack
+++ b/docker-pack
@@ -10,7 +10,7 @@
 #Parameters: None
 #Return: Nothing
 function usage() {
-    echo "Usage: $0 [-a file] [-b] [-c cmd] [-d] [-e cmd] [-f file] [-h] [-i] [-l log_file] [-n] [-p user] [-s template_file] [-t tag] [-u uid:gid] [-v version] [-w workdir] binary [binary] [binary] [binary]"
+    echo "Usage: $0 [-a file] [-b] [-c cmd] [-d] [-e cmd] [-f file] [-h] [-i] [-l log_file] [-n] [-p user] [-s template_file] [-t tag] [-u uid:gid] [-v version] [-w workdir] [-z /local/folder:/docker/dest:[VOLNAME]] binary [binary] [binary] [binary]"
     echo
     echo "-a file : A listing of files to add inside the docker image (absolute path, one file per line)"
     echo "-b      : Don't build the docker"
@@ -28,6 +28,7 @@ function usage() {
     echo "-u uid:gid : Define a uid:gid or user:group or user as docker will run (USER in dockerfile)"
     echo "-v version : Define Docker image version (default: 1.0)"
     echo "-w workdir : Working directory (default: $TEMP_DIR)"
+    echo "-z /local/folder=/docker/dest[:VOLNAME] : Include in docker a local folder (absolute path) to target folder (absolute path)"
     echo "Binary(ies) to put inside a docker"
     echo ""
     echo "Example: $0 /usr/bin/tar"
@@ -106,14 +107,14 @@ function findDependencies(){
     done |sort -u
 }
 
-#Name: prepareFilesToPack
-#Description: prepare all files needed for building docker: Copy bin + lib
+#Name: prepareBinToPack
+#Description: prepare files needed for building docker: Copy bin + lib
 #Parameters: Binary + list of libs
 #Return: Nothing
 #TODO: rewrite this function as it is badly writen...
-function prepareFilesToPack(){
-    debug "prepareFilesToPack $*"
-    [[ $# -lt 1 ]] && die "$0 -> ${FUNCNAME[0]}() : problem on number of parameters ($#)" 
+function prepareBinToPack(){
+    debug "prepareBinToPack $*"
+    [[ $# -lt 1 ]] && die "$0 -> ${FUNCNAME[0]}() : problem on number of parameters ($#)"
     local l_BIN=$1;shift
     local l_LIBS="$*"
     local l_FILE;local l_FILE_TARGET
@@ -147,6 +148,23 @@ function prepareFilesToPack(){
             #[ ${l_FILE} == ${l_BIN} ] && upx -q "${TEMP_DIR}${l_DIR}/${l_NAME}"
         fi
     done
+}
+
+#Name: prepareFolderToPack
+#Description: prepare folder to put inside docker
+#Parameters: LocalFolder DockerFolder
+#Return: Nothing
+function prepareFolderToPack(){
+    debug "prepareFolderToPack $*"
+    [[ $# -lt 1 ]] && die "$0 -> ${FUNCNAME[0]}() : problem on number of parameters ($#)"
+    local l_temp
+    l_temp=$1
+    local l_L_FOLDER=${l_temp/%\/};shift    #Remove the trailling /
+    local l_D_FOLDER=$1;shift
+    debug "Copy recursively $l_L_FOLDER to ${TEMP_DIR}${l_D_FOLDER}"
+    l_temp=$(echo "${TEMP_DIR}${l_D_FOLDER}"|sed -e"s%\/[^\/]*$%%")     #Remove last folder preventing when copying with -R copying folder inside same folder name
+    [[ -d "${TEMP_DIR}${l_D_FOLDER}" ]] || mkdir -p "$l_temp"
+    cp -R "$l_L_FOLDER"  "${TEMP_DIR}${l_D_FOLDER}"
 }
 
 #Name: generateLdLibraryPath
@@ -200,6 +218,10 @@ function generateDockerfile(){
     echo "ENV LD_LIBRARY_PATH $LD_LIBRARY_PATH"         >> "${TEMP_DIR}/Dockerfile"
     debug "Copying files in Dockerfile"
     echo "COPY . /"                                     >> "${TEMP_DIR}/Dockerfile"
+    if [[ $DATA_VOLUME != "" ]];then
+        debug "Configuring VOLUME in Dockerfile"
+        echo "VOLUME $DATA_VOLUME:$DATA_DIR_DOCKER"     >> "${TEMP_DIR}/Dockerfile"
+    fi
     debug "Configuring ENTRYPOINT"
     echo "ENTRYPOINT $ENTRYPOINT"                       >> "${TEMP_DIR}/Dockerfile"
     [[ $COMMAND != "" ]] && echo "CMD $COMMAND"         >> "${TEMP_DIR}/Dockerfile"
@@ -310,14 +332,31 @@ hosts:      files dns" > "${TEMP_DIR}/etc/nsswitch.conf"
 #Parameters: Files_list
 #Return: Nothing
 function areFilesPresent(){
+    debug "areFilesPresent $*"
     [[ $# -lt 1 ]] && die "$0 -> ${FUNCNAME[0]}() : problem on number of parameters ($#)"
     local l_list="$*"
     local l_file
     for l_file in $l_list; do
-        debug "Checking if file is in absolute path format"
+        debug "Checking if file $l_file is in absolute path format"
         [[ "$l_file" = /* ]] || die "File $l_file not in absolute path"
-        debug "Checking files present or not"
+        debug "Checking file $l_file present or not"
         [ -f "$l_file" ] || die "File not found: \"$l_file\", where is it ?"
+    done
+}
+
+#Name: areFoldersPresent
+#Description: Check if folders are present on disk
+#Parameters: Folders_list
+#Return: Nothing
+function areFoldersPresent(){
+    [[ $# -lt 1 ]] && die "$0 -> ${FUNCNAME[0]}() : problem on number of parameters ($#)"
+    local l_list="$*"
+    local l_folder
+    for l_folder in $l_list; do
+        debug "Checking if folder $l_folder is in absolute path format"
+        [[ "$l_folder" = /* ]] || die "File $l_folder not in absolute path"
+        debug "Checking folder $l_folder present or not"
+        [ -d "$l_folder" ] || die "File not found: \"$l_folder\", where is it ?"
     done
 }
 
@@ -466,7 +505,7 @@ SCRIPT_PID=$$
 
 checkPrerequisites
 
-while getopts ":a:bc:de:fhil:np:s:t:u:v:w:" opt; do
+while getopts ":a:bc:de:fhil:np:s:t:u:v:w:z:" opt; do
     case "$opt" in
     a)  #File listing file to pack
         if [ -f "$OPTARG" ]
@@ -523,6 +562,12 @@ while getopts ":a:bc:de:fhil:np:s:t:u:v:w:" opt; do
     w)  #Temp working directory
         TEMP_DIR=$OPTARG
         ;;
+    z)  #Include data folder
+        IFS_BCK=$IFS;IFS=":";read -ra TEMP <<< "$OPTARG";IFS=$IFS_BCK
+        DATA_DIR_LOCAL=${TEMP[0]}
+        DATA_DIR_DOCKER=${TEMP[1]}
+        DATA_VOLUME=${TEMP[2]}
+        ;;
     \?) usage; exit 0
         ;;
     :)  die "Option -$OPTARG requires an argument."
@@ -561,10 +606,14 @@ FIRSTBIN="$1"
 
 isDockerExisting "$TAG_NAME:$TAG_VERSION" || die "Docker already present, please remove it before (docker rmi $TAG_NAME:$TAG_VERSION)"
 areFilesPresent "${BINARIES}" "${FILELIST}" "${ADDFILES}"
+if [[ $DATA_DIR_LOCAL != "" ]];then 
+    areFoldersPresent "${DATA_DIR_LOCAL}"
+    prepareFolderToPack "${DATA_DIR_LOCAL}" "${DATA_DIR_DOCKER}"
+fi
 separateFileType "${BINARIES}" "${FILELIST}"
 SCRIPTBINARIES=$(findScriptBinaries "${SCRIPTFILES}")
 DEPENDENCIES=$(findDependencies "${BINARIES} ${SCRIPTBINARIES}")
-prepareFilesToPack "${DEPENDENCIES}" "${SCRIPTFILES}" "${ADDFILES}"
+prepareBinToPack "${DEPENDENCIES}" "${SCRIPTFILES}" "${ADDFILES}"
 [[ $DOWNTINI == 1 ]] && addTini
 generateLdLibraryPath "${BINARIES}" "${DEPENDENCIES}"
 generateDockerfile
