Moved help section at top, changed function name to camel coding, ...

diff --git a/docker-pack b/docker-pack
--- a/docker-pack
+++ b/docker-pack
@@ -2,8 +2,38 @@
 
 #Script to create a docker image without using an OS but from scratch an binarie dependencies
 #Avantages: Smallest image, less security problem, ...
+#https://github.com/DavidTre07/docker-pack
 #Author: david.tre07@gmail.com
-DPACKRELEASE=1.0
+
+#TODO: Add fonts with an option
+
+#Name: usage
+#Description: Print out usage
+#Parameters: None
+#Return: Nothing
+function usage() {
+    echo "Usage: $0 [-b] [-c cmd] [-d] [-e cmd] [-f file] [-h] [-l log_file] [-n] [-p user] [-s template_file] [-t tag] [-u uid:gid] [-v version] [-w workdir] binary [binary] [binary] [binary]"
+    echo
+    echo "-b      : Don't build the docker"
+    echo "-c cmd  : Define command to run on docker CMD"
+    echo "-d      : Debug mode"
+    echo "-e cmd  : Define entrypoint (default: 1st binary)"
+    echo "-f file : A file listing files to add inside the docker image (absolute path, one file per line)"
+    echo "-h      : This Help"
+    echo "-l file : Log into a file"
+    echo "-n      : Activate nslookup"
+    echo "-p user : Activate password file with an account provided as parameter"
+    echo "-s file : Dockerfile template file (if not provided a default one will be generated)"
+    echo "-t tag  : Define Docker image tag (default: 1st binary name)"
+    echo "-u uid:gid : Define a uid:gid as docker will run (USER in dockerfile)"
+    echo "-v version : Define Docker image version (default: 1.0)"
+    echo "-w workdir : Working directory (default: /tmp/docker-pack)"
+    echo "Binary(ies) to put inside a docker"
+    echo ""
+    echo "Example: $0 /usr/bin/tar"
+    echo "         To run it: docker run --rm tar:1.0 --help"
+    echo
+}
 
 #Wrap pushd and popd to be silent
 function pushd() {
@@ -39,12 +69,13 @@ function debug() {
     [[ $DEBUG == 1 ]] && echo "  DEBUG: $*" >&2
 }
 
-#Name: check_prerequisites
+#Name: checkPrerequisites
 #Description: Verify all prerequisites
 #Parameters: None
 #Return: Nothing
-function check_prerequisites() {
+function checkPrerequisites() {
     debug "Checking prerequisites"
+    [[ $# -ne 0 ]] && die "$0 -> ${FUNCNAME}() : problem on number of parameters ($#)"
     command -v docker >/dev/null || die "Missing binary: docker"
     debug "docker is available"
     command -v ldd >/dev/null || die "Missing binary: ldd"
@@ -53,25 +84,31 @@ function check_prerequisites() {
     [ -d $TEMP_DIR ] && die "Temp folder $TEMP_DIR already exist"
 }
 
-#Name: find_dependencies
+#Name: findDependencies
 #Description: Detect binary dependencies
 #Parameters: Binary
 #Return: Nothing
-function find_dependencies(){
+function findDependencies(){
+    [[ $# -lt 1 ]] && die "$0 -> ${FUNCNAME}() : problem on number of parameters ($#)"
     local l_BIN="$@"
+    debug "Checking if all binaries are bin files"
+    exitIfNotElf $l_BIN
     debug "Finding dependencies of $l_BIN"
+    #Also print binary itself
     msg $l_BIN
+    #If shared lib then print dependencies
     ldd $l_BIN | grep "/" |sed -e"/:$/d" -e"s%[^/]*/%/%" -e"s%(.*)%%" -e"s%:$%%" |sort -u
 }
 
-#Name: prepare_docker_env
+#Name: prepareDockerEnv
 #Description: prepare all files needed for building docker:
 #       Copy bin + lib
 #       Generate LD_LIBRARY_PATH
 #Parameters: Binary + list of libs
 #Return: Nothing
-function prepare_docker_env(){
-    debug "prepare_docker_env $@"
+function prepareDockerEnv(){
+    debug "prepareDockerEnv $@"
+    [[ $# -lt 1 ]] && die "$0 -> ${FUNCNAME}() : problem on number of parameters ($#)"
     local l_BIN=$1;shift
     local l_LIBS="$@"
     local l_FILE
@@ -96,17 +133,19 @@ function prepare_docker_env(){
     debug "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
 }
 
-#Name: generate_dockerfile
+#Name: generateDockerfile
 #Description: replace vars on template dockerfile
 #Parameters: None
 #Return: Nothing
-function generate_dockerfile(){
+function generateDockerfile(){
+    debug "Generating Dockerfile"
+    [[ $# -ne 0 ]] && die "$0 -> ${FUNCNAME}() : problem on number of parameters ($#)"
     if [[ $TEMPLATE_FILE == "" ]];then
         echo 'FROM scratch' >${TEMP_DIR}/Dockerfile
     else
         cp $TEMPLATE_FILE ${TEMP_DIR}/Dockerfile
     fi
-    sed -i -e"1i#Generated docker by docker-pack $DPACKRELEASE (david.tre07@gmail.com)" ${TEMP_DIR}/Dockerfile
+    sed -i -e"1i#Generated by docker-pack (https://github.com/DavidTre07/docker-pack)" ${TEMP_DIR}/Dockerfile
     echo "ENV LD_LIBRARY_PATH $LD_LIBRARY_PATH" >> ${TEMP_DIR}/Dockerfile
     echo "COPY . /" >> ${TEMP_DIR}/Dockerfile
     [[ $USERID != "" ]] && echo "USER $USERID" >> ${TEMP_DIR}/Dockerfile
@@ -114,20 +153,22 @@ function generate_dockerfile(){
     [[ $COMMAND != "" ]] && echo "CMD [\"$COMMAND\"]" >> ${TEMP_DIR}/Dockerfile
 }
 
-#Name: clean_docker_env
+#Name: cleanDockerEnv
 #Description: Cleanup docker env
 #Parameters: None
 #Return: Nothing
-function clean_docker_env(){
+function cleanDockerEnv(){
     debug "Cleaning temp folder"
+    [[ $# -ne 0 ]] && die "$0 -> ${FUNCNAME}() : problem on number of parameters ($#)"
     rm -fr ${TEMP_DIR}
 }
 
-#Name: build_dockerimage
+#Name: buildDockerimage
 #Description: Build docker image
 #Parameters: None (use global vars)
 #Return: Nothing
-function build_dockerimage(){
+function buildDockerimage(){
+    [[ $# -ne 0 ]] && die "$0 -> ${FUNCNAME}() : problem on number of parameters ($#)"
     #If no tag provided then generate one
     if [[ $TAG_NAME == "" ]];then
         [[ $COMMAND != "" ]] && TAG_NAME=${COMMAND##*/}
@@ -140,12 +181,13 @@ function build_dockerimage(){
     popd
 }
 
-#Name: activate_passwd
+#Name: activatePasswd
 #Description: Add files in docker so /etc/passwd will works
 #Parameters: user
 #Return: Nothing
-function activate_passwd(){
+function activatePasswd(){
     debug "Generating /etc/passwd"
+    [[ $# -ne 1 ]] && die "$0 -> ${FUNCNAME}() : problem on number of parameters ($#)"
     local l_user=$1;shift
     #Generate a small passwd and shadow
     [ -d "${TEMP_DIR}/etc" ] || mkdir -p ${TEMP_DIR}/etc
@@ -154,12 +196,13 @@ function activate_passwd(){
     echo "/lib64/libnss_files.so.2"
 }
 
-#Name: activate_nslookup
+#Name: activateNslookup
 #Description: Add files in docker so nslookup will works
 #Parameters: None
 #Return: Nothing
-function activate_nslookup(){
+function activateNslookup(){
     debug "Generating nsswitch.conf"
+    [[ $# -ne 0 ]] && die "$0 -> ${FUNCNAME}() : problem on number of parameters ($#)"
     [ -d "${TEMP_DIR}/etc" ] || mkdir -p ${TEMP_DIR}/etc
     echo "passwd:     files
 shadow:     files
@@ -168,12 +211,13 @@ hosts:      files dns" > "${TEMP_DIR}/etc/nsswitch.conf"
     echo "/lib64/libnss_dns.so.2"
 }
 
-#Name: are_files_present
+#Name: areFilesPresent
 #Description: Check if files are present on disk
 #Parameters: Files_list
 #Return: Nothing
-function are_files_present(){
+function areFilesPresent(){
     debug "Checking files present or not"
+    [[ $# -lt 1 ]] && die "$0 -> ${FUNCNAME}() : problem on number of parameters ($#)"
     local l_list="$@"
     local l_file
     for l_file in $l_list; do
@@ -181,42 +225,30 @@ function are_files_present(){
     done
 }
 
-#Name: serialize_file
+#Name: serializeFile
 #Description: Serialize file list and remove comments
 #Parameters: file_list
 #Return: Nothing
-function serialize_file(){
+function serializeFile(){
     debug "Adding additional files"
+    [[ $# -ne 1 ]] && die "$0 -> ${FUNCNAME}() : problem on number of parameters ($#)"
     local l_filelist=$1;shift
     cat $l_filelist | grep -v "^#" | tr '\n' ' '
 }
 
-#Name: usage
-#Description: Print out usage
-#Parameters: None
+#Name: exitIfNotElf
+#Description: detect if binary is an ELF file
+#Parameters: binaries
 #Return: Nothing
-function usage() {
-    echo "Usage: $0 [-b] [-c cmd] [-d] [-e cmd] [-f file] [-h] [-l log_file] [-n] [-p user] [-s template_file] [-t tag] [-u uid:gid] [-v version] [-w workdir] binary [binary] [binary] [binary]"
-    echo
-    echo "-b      : Don't build the docker"
-    echo "-c cmd  : Define command to run on docker CMD"
-    echo "-d      : Debug mode"
-    echo "-e cmd  : Define entrypoint (default: 1st binary)"
-    echo "-f file : A file listing files to add inside the docker image (absolute path, one file per line)"
-    echo "-h      : This Help"
-    echo "-l file : Log into a file"
-    echo "-n      : Activate nslookup"
-    echo "-p user : Activate password file with an account provided as parameter"
-    echo "-s file : Dockerfile template file (if not provided a default one will be generated)"
-    echo "-t tag  : Define Docker image tag (default: 1st binary name)"
-    echo "-u uid:gid : Define a uid:gid as docker will run (USER in dockerfile)"
-    echo "-v version : Define Docker image version (default: 1.0)"
-    echo "-w workdir : Working directory (default: /tmp/docker-pack)"
-    echo "Binary(ies) to put inside a docker"
-    echo ""
-    echo "Example: $0 /usr/bin/tar"
-    echo "         To run it: docker run --rm tar:1.0 --help"
-    echo
+function exitIfNotElf(){
+    debug "Checking if binary is an ELF file"
+    [[ $# -lt 1 ]] && die "$0 -> ${FUNCNAME}() : problem on number of parameters ($#)"
+    local l_listOfSupportedType="application/x-sharedlib|application/x-executable"
+    local l_binaries="$@"
+    for l_binary in $l_binaries; do
+        file -i `readlink -f $l_binary` | grep -E "$l_listOfSupportedType" >/dev/null 2>&1
+        [[ $? -eq 1 ]] && die "File \"$l_binary\" is not an executable..."
+    done
 }
 
 ########## MAIN ##########
@@ -239,7 +271,7 @@ while getopts ":bc:de:f:l:hnp:s:t:u:v:w:" opt; do
         ;;
     e)  ENTRYPOINT=$OPTARG
         ;;
-    f)  [ -f $OPTARG ] && ADDFILES="$ADDFILES $(serialize_file $OPTARG)" || die "File not found: $OPTARG" 
+    f)  [ -f $OPTARG ] && ADDFILES="$ADDFILES $(serializeFile $OPTARG)" || die "File not found: $OPTARG" 
         ;;
     h)  usage; exit 0
         ;;
@@ -267,25 +299,25 @@ while getopts ":bc:de:f:l:hnp:s:t:u:v:w:" opt; do
     esac
 done
 shift $((OPTIND-1))
-if [ $# -lt 1 ];then usage; exit 1; fi
+if [ $# -lt 1 ];then usage; die "Missing a binary file to pack"; fi
 BINARIES="$@"
 
-check_prerequisites
+checkPrerequisites
 #Generate a list of additional libs
-[[ $NSLOOKUP == "1" ]] && ADDONS="$ADDONS $(activate_nslookup)"
-[[ $PASSWD == "1" ]] && ADDONS="$ADDONS $(activate_passwd $OPTARG)"
+[[ $NSLOOKUP == "1" ]] && ADDONS="$ADDONS $(activateNslookup)"
+[[ $PASSWD == "1" ]] && ADDONS="$ADDONS $(activatePasswd $OPTARG)"
 #If no command provided and no entrypoint then set 1st bin as default entrypoint
 if [[ $COMMAND == "" ]];then
     [[ $ENTRYPOINT == "" ]] && ENTRYPOINT=$1
 fi
 
-are_files_present ${BINARIES} ${ADDONS} ${ADDFILES}
-prepare_docker_env $(find_dependencies ${BINARIES} ${ADDONS}) ${ADDFILES}
-generate_dockerfile
+areFilesPresent ${BINARIES} ${ADDONS} ${ADDFILES}
+prepareDockerEnv $(findDependencies ${BINARIES} ${ADDONS}) ${ADDFILES}
+generateDockerfile
 
 if [[ $DOCKER_BUILD == 1 ]];then
-    build_dockerimage
-    clean_docker_env
+    buildDockerimage
+    cleanDockerEnv
 else
     msg "Docker is ready to build in folder: ${TEMP_DIR}"
     msg "You can build it with: cd ${TEMP_DIR}; docker -t docker_name:1.0 ."
