Added fonts option, file type detection for dynamic lib detection

diff --git a/docker-pack b/docker-pack
--- a/docker-pack
+++ b/docker-pack
@@ -58,10 +58,13 @@ function check_prerequisites() {
 #Parameters: Binary
 #Return: Nothing
 function find_dependencies(){
-    local l_BIN="$@"
-    debug "Finding dependencies of $l_BIN"
-    msg $l_BIN
-    ldd $l_BIN | grep "/" |sed -e"/:$/d" -e"s%[^/]*/%/%" -e"s%(.*)%%" -e"s%:$%%" |sort -u
+    local l_BINARIES="$@"
+    local l_BIN
+    debug "Finding dependencies of $l_BINARIES"
+    msg $l_BINARIES
+    for l_BIN in $l_BINARIES;do
+        ldd $l_BIN | grep "/" |sed -e"/:$/d" -e"s%[^/]*/%/%" -e"s%(.*)%%" -e"s%:$%%"
+    done |sort -u
 }
 
 #Name: prepare_docker_env
@@ -89,7 +92,7 @@ function prepare_docker_env(){
             [[  ${l_FILE} != ${l_BIN} ]] && LD_LIBRARY_PATH="$LD_LIBRARY_PATH:${l_DIR}"
         fi
         debug "cp $l_FILE ${TEMP_DIR}${l_DIR}"
-        cp $l_FILE ${TEMP_DIR}${l_DIR}
+        cp -p $l_FILE ${TEMP_DIR}${l_DIR}
         #Compress file
         #[ ${l_FILE} == ${l_BIN} ] && upx -q "${TEMP_DIR}${l_DIR}/${l_NAME}"
     done
@@ -191,18 +194,54 @@ function serialize_file(){
     cat $l_filelist | grep -v "^#" | tr '\n' ' '
 }
 
+#Name: add_fonts
+#Description: Add fonts inside docker
+#Parameters:  None
+#Return: Nothing
+function add_fonts(){
+    #Fonts list
+    local l_fontslist="/usr/share/fonts/google-droid/DroidSans.ttf"
+    echo $l_fontslist
+}
+
+#Name: separate_file_type
+#Description: In the file list provided, determine which are ELF or not
+#Parameters:  filelist
+#Return: Nothing
+function separate_file_type(){
+    local l_filelist=$@
+    local l_file
+    #Empty filelist
+    BINARIES=""; ADDFILES=""
+    for l_file in $l_filelist;do
+        case "$(file $(readlink -f $l_file))" in
+        *ELF*) debug "$l_file: ELF"
+            BINARIES="$BINARIES $l_file"
+            ;;
+        *"shell script"*) debug "$l_file: Script"
+            ADDFILES="$ADDFILES $l_file"
+            msg "Warning: $l_file is a shell script, you need to check inside script what binaries are used."
+            ;;
+        *) debug "$l_file: Other file"
+            ADDFILES="$ADDFILES $l_file"
+            ;;
+        esac
+    done
+}
+
 #Name: usage
 #Description: Print out usage
 #Parameters: None
 #Return: Nothing
 function usage() {
-    echo "Usage: $0 [-b] [-c cmd] [-d] [-e cmd] [-f file] [-h] [-l log_file] [-n] [-p user] [-s template_file] [-t tag] [-u uid:gid] [-v version] [-w workdir] binary [binary] [binary] [binary]"
+    echo "Usage: $0 [-a file] [-b] [-c cmd] [-d] [-e cmd] [-f file] [-h] [-l log_file] [-n] [-p user] [-s template_file] [-t tag] [-u uid:gid] [-v version] [-w workdir] binary [binary] [binary] [binary]"
     echo
+    echo "-a file : A listing of files to add inside the docker image (absolute path, one file per line)"
     echo "-b      : Don't build the docker"
     echo "-c cmd  : Define command to run on docker CMD"
     echo "-d      : Debug mode"
     echo "-e cmd  : Define entrypoint (default: 1st binary)"
-    echo "-f file : A file listing files to add inside the docker image (absolute path, one file per line)"
+    echo "-f      : Add font inside docker"
     echo "-h      : This Help"
     echo "-l file : Log into a file"
     echo "-n      : Activate nslookup"
@@ -224,13 +263,15 @@ COMMAND="";ENTRYPOINT=""
 DOCKER_BUILD=1;DEBUG=0
 TEMPLATE_FILE=""
 TAG_NAME="";TAG_VERSION="1.0"
-USERID="";ADDONS="";ADDFILES=""
+USERID="";ADDFILES=""
 LD_LIBRARY_PATH="."
 NSLOOKUP=0;PASSWD=0
 TEMP_DIR="/tmp/docker-pack"
 
-while getopts ":bc:de:f:l:hnp:s:t:u:v:w:" opt; do
+while getopts ":a:bc:de:fl:hnp:s:t:u:v:w:" opt; do
     case "$opt" in
+    a)  [ -f $OPTARG ] && ADDFILES="$ADDFILES $(serialize_file $OPTARG)" || die "File not found: $OPTARG" 
+        ;;
     b)  DOCKER_BUILD=0
         ;;
     c)  COMMAND=$OPTARG
@@ -239,7 +280,7 @@ while getopts ":bc:de:f:l:hnp:s:t:u:v:w:" opt; do
         ;;
     e)  ENTRYPOINT=$OPTARG
         ;;
-    f)  [ -f $OPTARG ] && ADDFILES="$ADDFILES $(serialize_file $OPTARG)" || die "File not found: $OPTARG" 
+    f)  ADDFILES="$ADDFILES $(add_fonts)" 
         ;;
     h)  usage; exit 0
         ;;
@@ -272,15 +313,16 @@ BINARIES="$@"
 
 check_prerequisites
 #Generate a list of additional libs
-[[ $NSLOOKUP == "1" ]] && ADDONS="$ADDONS $(activate_nslookup)"
-[[ $PASSWD == "1" ]] && ADDONS="$ADDONS $(activate_passwd $OPTARG)"
+[[ $NSLOOKUP == "1" ]] && ADDFILES="$ADDFILES $(activate_nslookup)"
+[[ $PASSWD == "1" ]] && ADDFILES="$ADDFILES $(activate_passwd $OPTARG)"
 #If no command provided and no entrypoint then set 1st bin as default entrypoint
 if [[ $COMMAND == "" ]];then
     [[ $ENTRYPOINT == "" ]] && ENTRYPOINT=$1
 fi
 
-are_files_present ${BINARIES} ${ADDONS} ${ADDFILES}
-prepare_docker_env $(find_dependencies ${BINARIES} ${ADDONS}) ${ADDFILES}
+are_files_present ${BINARIES} ${ADDFILES}
+separate_file_type ${BINARIES} ${ADDFILES}
+prepare_docker_env $(find_dependencies ${BINARIES}) ${ADDFILES}
 generate_dockerfile
 
 if [[ $DOCKER_BUILD == 1 ]];then
